name: unexplored paradises
markdown: redcarpet
description: "When I can, I travel. When I can't travel, I dream about my next adventure and collect images of places I want to visit."
url: http://unexploredparadises.eu
permalink: /:title
fbappid: 244999072358409 # facebook app ID
paginate: 12
paginate_path: "/:num"
