name: unexplored paradises
markdown: redcarpet
description: "A photoblog dedicated to discovering less known beautiful places around the world."
url: http://unexploredparadises.eu
permalink: /:title
fbappid: 244999072358409 # facebook app ID
